#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cord_yy_create_buffer
#define yy_delete_buffer cord_yy_delete_buffer
#define yy_scan_buffer cord_yy_scan_buffer
#define yy_scan_string cord_yy_scan_string
#define yy_scan_bytes cord_yy_scan_bytes
#define yy_init_buffer cord_yy_init_buffer
#define yy_flush_buffer cord_yy_flush_buffer
#define yy_load_buffer_state cord_yy_load_buffer_state
#define yy_switch_to_buffer cord_yy_switch_to_buffer
#define yypush_buffer_state cord_yypush_buffer_state
#define yypop_buffer_state cord_yypop_buffer_state
#define yyensure_buffer_stack cord_yyensure_buffer_stack
#define yy_flex_debug cord_yy_flex_debug
#define yyin cord_yyin
#define yyleng cord_yyleng
#define yylex cord_yylex
#define yylineno cord_yylineno
#define yyout cord_yyout
#define yyrestart cord_yyrestart
#define yytext cord_yytext
#define yywrap cord_yywrap
#define yyalloc cord_yyalloc
#define yyrealloc cord_yyrealloc
#define yyfree cord_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define cord_yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer cord_yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define cord_yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer cord_yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define cord_yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer cord_yy_scan_buffer
#endif

#ifdef yy_scan_string
#define cord_yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string cord_yy_scan_string
#endif

#ifdef yy_scan_bytes
#define cord_yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes cord_yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define cord_yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer cord_yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define cord_yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer cord_yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define cord_yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state cord_yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define cord_yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer cord_yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define cord_yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state cord_yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define cord_yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state cord_yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define cord_yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack cord_yyensure_buffer_stack
#endif

#ifdef yylex
#define cord_yylex_ALREADY_DEFINED
#else
#define yylex cord_yylex
#endif

#ifdef yyrestart
#define cord_yyrestart_ALREADY_DEFINED
#else
#define yyrestart cord_yyrestart
#endif

#ifdef yylex_init
#define cord_yylex_init_ALREADY_DEFINED
#else
#define yylex_init cord_yylex_init
#endif

#ifdef yylex_init_extra
#define cord_yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra cord_yylex_init_extra
#endif

#ifdef yylex_destroy
#define cord_yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy cord_yylex_destroy
#endif

#ifdef yyget_debug
#define cord_yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug cord_yyget_debug
#endif

#ifdef yyset_debug
#define cord_yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug cord_yyset_debug
#endif

#ifdef yyget_extra
#define cord_yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra cord_yyget_extra
#endif

#ifdef yyset_extra
#define cord_yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra cord_yyset_extra
#endif

#ifdef yyget_in
#define cord_yyget_in_ALREADY_DEFINED
#else
#define yyget_in cord_yyget_in
#endif

#ifdef yyset_in
#define cord_yyset_in_ALREADY_DEFINED
#else
#define yyset_in cord_yyset_in
#endif

#ifdef yyget_out
#define cord_yyget_out_ALREADY_DEFINED
#else
#define yyget_out cord_yyget_out
#endif

#ifdef yyset_out
#define cord_yyset_out_ALREADY_DEFINED
#else
#define yyset_out cord_yyset_out
#endif

#ifdef yyget_leng
#define cord_yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng cord_yyget_leng
#endif

#ifdef yyget_text
#define cord_yyget_text_ALREADY_DEFINED
#else
#define yyget_text cord_yyget_text
#endif

#ifdef yyget_lineno
#define cord_yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno cord_yyget_lineno
#endif

#ifdef yyset_lineno
#define cord_yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno cord_yyset_lineno
#endif

#ifdef yywrap
#define cord_yywrap_ALREADY_DEFINED
#else
#define yywrap cord_yywrap
#endif

#ifdef yyalloc
#define cord_yyalloc_ALREADY_DEFINED
#else
#define yyalloc cord_yyalloc
#endif

#ifdef yyrealloc
#define cord_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc cord_yyrealloc
#endif

#ifdef yyfree
#define cord_yyfree_ALREADY_DEFINED
#else
#define yyfree cord_yyfree
#endif

#ifdef yytext
#define cord_yytext_ALREADY_DEFINED
#else
#define yytext cord_yytext
#endif

#ifdef yyleng
#define cord_yyleng_ALREADY_DEFINED
#else
#define yyleng cord_yyleng
#endif

#ifdef yyin
#define cord_yyin_ALREADY_DEFINED
#else
#define yyin cord_yyin
#endif

#ifdef yyout
#define cord_yyout_ALREADY_DEFINED
#else
#define yyout cord_yyout
#endif

#ifdef yy_flex_debug
#define cord_yy_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug cord_yy_flex_debug
#endif

#ifdef yylineno
#define cord_yylineno_ALREADY_DEFINED
#else
#define yylineno cord_yylineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cord_yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[362] =
    {   0,
        0,    0,   64,   64,   71,   69,   61,   62,   69,   69,
       69,   69,   69,   69,   54,   69,   69,   69,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   69,   64,   65,
       66,   61,   49,    0,   59,    0,   60,   46,   57,   63,
       56,   54,    0,   52,   50,   48,   51,   53,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,    0,    0,    0,
       47,   64,   65,   66,   67,   66,   68,    0,   56,    0,

        0,   55,   58,   58,   58,   58,   58,    8,   58,    6,
       11,   58,   58,   58,   58,   58,   58,   58,   12,   58,
       58,   58,   10,   58,   58,   58,    7,   58,   58,    9,
       58,   58,    0,    0,    0,    0,    0,    0,    0,   57,
        0,    0,   56,   58,   58,   58,   17,   58,   58,   58,
        0,   33,   19,   58,   18,    2,   58,   58,    1,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   14,   58,
       58,   58,    0,    0,    0,    0,    0,    0,    0,   56,
       58,   58,   58,   58,   58,   58,   16,    0,   45,   15,
       58,   13,   58,   58,   58,   58,   58,   58,    0,   35,

       58,   58,   58,   58,    0,    0,    0,    0,    0,    0,
        0,   43,   58,    0,   58,   58,   58,   20,   58,   58,
       58,   58,   58,   58,   58,    0,    0,   32,   58,   58,
        0,    0,    0,    0,    0,    0,   58,    0,   58,   58,
       58,   58,   58,    0,   34,   58,   58,   58,   58,    0,
        0,    0,   42,   58,    0,    0,   39,    0,    0,   40,
        0,    0,   41,   58,    0,   58,   58,    0,   58,   58,
       58,   58,    0,   58,    0,    0,   58,    0,    0,    0,
        0,   44,    0,   58,   58,    0,   58,    0,   30,   25,
       58,    0,    0,   58,    0,    0,   58,    0,   36,    0,

       37,    0,   38,    4,   58,   58,    0,   58,   58,    0,
        0,   24,    0,    0,   58,    0,   29,   58,    0,   21,
       58,    0,    0,    0,    0,   27,    0,   23,    0,   58,
        0,    0,    0,    0,    0,   31,   58,    0,    0,    0,
        0,    0,    0,    0,    0,   28,    0,    0,    0,    0,
        5,    0,    0,    0,    0,    0,   26,    3,    0,   22,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    1,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,    1,    1,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
        1,    1,    1,    1,   29,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   29,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,    1,   71,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    3,    3,    3,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1
    } ;

static const flex_int16_t yy_base[368] =
    {   0,
        0,    0,   69,   70,  400,  804,   72,  804,  376,  350,
      350,  343,   66,  341,   71,   71,  288,   72,   44,   60,
       68,    0,   68,   83,   47,   64,   76,   85,   67,  100,
       72,  101,  114,  108,  256,  255,  246,  180,  227,  804,
      135,  145,  804,  206,  804,  203,  804,  804,  141,  804,
      147,  165,  172,  804,  804,  804,  804,  804,    0,  125,
      127,   89,  130,  136,  140,  149,  141,  172,  161,  162,
      172,  171,  168,  171,  179,  168,  176,  172,  168,  191,
      172,  183,  183,  180,  198,  203,  194,  210,  212,  213,
      804,  170,  804,  249,  804,  250,  804,  266,  240,  273,

      209,  277,  233,  236,  251,  247,  241,  257,  263,  294,
        0,  259,  266,  278,  279,  281,  273,  284,  294,  286,
      292,  295,    0,  293,  293,  294,  281,  284,  287,    0,
      293,  306,  289,  290,  293,  295,  297,  298,  350,  353,
      360,  363,  366,  327,  334,  329,    0,  322,  339,  361,
      385,  804,    0,  351,    0,    0,  388,  352,  373,  138,
      358,  359,  374,  378,  364,  365,  405,  366,    0,  366,
      384,  377,  380,  383,  383,  386,  386,  391,  417,  430,
      434,  408,  112,  404,  408,  416,    0,  449,  804,    0,
      413,    0,  427,  428,  421,  425,  432,  424,  459,  804,

      430,  467,  426,  442,  449,  448,  455,  455,  459,  464,
      489,  804,  455,  469,  477,  461,  461,    0,  462,  483,
      509,  477,  478,  480,  482,  514,  495,  804,  533,  475,
      488,  537,  496,  540,  498,  545,  487,  506,  522,  518,
      102,  527,  526,  557,  804,  532,  542,   95,  541,  535,
      533,  567,  804,  539,  535,  585,  804,  536,  592,  804,
      537,  598,  804,  602,  551,  550,  553,  545,  561,  609,
      590,  562,  584,  597,  597,  599,  603,  627,  628,  632,
      633,  804,  605,  575,  610,  597,  614,  651,  804,    0,
      628,  622,  637,  629,  629,  634,  625,  661,  804,  670,

      804,  671,  804,  804,  678,  644,  632,  649,  633,  650,
      654,    0,  653,  696,   92,  697,  804,  662,  670,    0,
      684,  685,  686,  675,  705,  804,  678,    0,  709,  681,
      680,  698,  682,  698,  722,  804,   89,  697,  694,  732,
      691,  712,  702,  712,  745,  804,  712,  707,  725,  727,
      804,  728,  726,  737,  737,  733,  804,  804,  740,  804,
      804,  788,  791,  794,   74,  797,  800
    } ;

static const flex_int16_t yy_def[368] =
    {   0,
      361,    1,  362,  362,  361,  361,  361,  361,  361,  363,
      364,  361,  361,  361,  361,  361,  361,  361,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  361,  366,  361,
      367,  361,  361,  363,  361,  364,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  361,  361,  361,
      361,  366,  361,  367,  361,  367,  361,  361,  361,  361,

      361,  361,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  365,  365,  365,  365,  365,  365,  365,
      361,  361,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  361,  361,  361,  361,  361,  361,  361,  361,
      365,  365,  365,  365,  365,  365,  365,  361,  361,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  361,  361,

      365,  365,  365,  365,  361,  361,  361,  361,  361,  361,
      361,  361,  365,  361,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  361,  361,  361,  365,  365,
      361,  361,  361,  361,  361,  361,  365,  361,  365,  365,
      365,  365,  365,  361,  361,  365,  365,  365,  365,  361,
      361,  361,  361,  365,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  365,  361,  365,  365,  361,  365,  365,
      365,  365,  361,  365,  361,  361,  365,  361,  361,  361,
      361,  361,  361,  365,  365,  361,  365,  361,  361,  365,
      365,  361,  361,  365,  361,  361,  365,  361,  361,  361,

      361,  361,  361,  361,  365,  365,  361,  365,  365,  361,
      361,  365,  361,  361,  365,  361,  361,  365,  361,  365,
      365,  361,  361,  361,  361,  361,  361,  365,  361,  365,
      361,  361,  361,  361,  361,  361,  365,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
        0,  361,  361,  361,  361,  361,  361
    } ;

static const flex_int16_t yy_nxt[876] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,    6,    6,
        6,   13,   14,   15,   15,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   22,   22,   22,
       27,   28,   29,   22,   30,   31,   32,   33,   34,   22,
       22,   22,   35,   36,   37,   19,   20,   21,   22,   23,
       24,   25,   26,   22,   22,   27,   28,   29,   22,   30,
       31,   32,   33,   34,   22,   22,   22,   35,   36,   37,
       38,   40,   40,   42,   60,   42,   59,   41,   41,   49,
       49,   49,   51,   71,   52,   52,   52,   54,   55,   57,
       58,   63,  342,   61,   53,  327,   62,   72,   65,   60,

       66,   64,   68,   74,   76,  273,   77,   73,   71,   75,
       67,   80,  268,   69,   70,  214,  105,   63,   61,   78,
       53,   62,   72,   65,   81,   66,   64,   86,   68,   74,
       76,   77,   73,   79,   75,   67,   80,   95,   69,   70,
       82,   83,  105,   96,   87,   78,   42,   97,   42,   84,
       81,  192,   85,   86,   49,   49,   49,  106,   79,  103,
       99,   99,   99,  109,   98,   82,  104,   83,  107,   87,
      100,  110,   93,  108,   84,  111,   51,   85,   52,   52,
       52,  101,  101,  106,  103,  102,  102,  102,   53,  109,
       98,  104,  112,  107,  113,  114,  100,  110,  108,  115,

      111,  116,  117,  118,  119,   47,  120,  121,  122,  123,
      124,   45,  125,  126,   53,  127,  128,  129,  112,  113,
      114,  132,  102,  102,  102,  115,  116,  117,  118,   93,
      119,  120,  121,  122,  123,  130,  124,  125,  126,  131,
      127,  128,  133,  129,  135,  137,  134,  132,  136,  138,
       91,   95,   95,   99,   99,   99,   90,  361,   96,  144,
      130,  361,   97,  141,  131,   89,   88,  133,  145,  135,
      137,  134,  146,  136,  138,  139,  139,  147,  148,  140,
      140,  140,  142,  142,  149,  144,  143,  143,  143,  141,
      102,  102,  102,  145,  150,  151,  153,  151,  146,  154,

      155,  156,  147,  148,  157,   56,  158,  159,  160,  162,
      149,  152,  163,  161,  164,  165,  166,  167,  171,  150,
      168,  153,  169,  170,  154,  172,  155,  156,  173,  174,
      157,  158,  175,  159,  176,  162,  177,  178,  163,  161,
      164,  165,  166,  167,  171,  168,  181,  169,  170,   50,
       48,  172,   47,  173,  174,   45,  182,  175,  183,  176,
      184,  177,  178,  140,  140,  140,  140,  140,  140,  179,
      179,  185,  181,  180,  180,  180,  143,  143,  143,  143,
      143,  143,  182,  183,  186,  184,  151,  187,  151,  188,
      190,  188,  191,   43,  193,  194,  185,  195,  196,  361,

      197,  198,  152,  201,  202,  189,  199,  203,  199,  204,
      186,  205,  187,  206,  207,  190,  208,  209,  191,  193,
      194,  210,  200,  195,  196,  197,  198,  213,  201,  202,
      180,  180,  180,  203,  204,  211,  205,  211,  206,  207,
      215,  208,  209,  180,  180,  180,  210,  216,  217,  218,
      188,  212,  188,  213,  219,  220,  361,  221,  222,  223,
      199,  224,  199,  225,  229,  215,  189,  230,  226,  231,
      226,  232,  216,  217,  218,  233,  200,  227,  234,  235,
      219,  220,  221,  222,  228,  223,  224,  236,  225,  229,
      211,  237,  211,  230,  238,  231,  239,  232,  240,  241,

      242,  233,  243,  248,  234,  235,  212,  246,  247,  249,
      244,  255,  244,  236,  254,  226,  237,  226,  250,  258,
      238,  261,  239,  240,  241,  242,  245,  251,  243,  248,
      264,  228,  246,  247,  252,  249,  252,  255,  256,  254,
      256,  259,  265,  259,  250,  258,  262,  261,  262,  266,
      253,  267,  251,  269,  257,  264,  270,  260,  244,  271,
      244,  272,  263,  274,  361,  275,  276,  265,  252,  277,
      252,  278,  279,  280,  245,  266,  267,  361,  283,  269,
      285,  270,  284,  286,  253,  271,  256,  272,  256,  274,
      275,  276,  287,  259,  277,  259,  278,  279,  280,  262,

      291,  262,  257,  281,  283,  281,  285,  284,  286,  260,
      288,  290,  288,  305,  292,  263,  294,  287,  293,  282,
      295,  296,  297,  361,  361,  291,  289,  304,  298,  300,
      298,  300,  306,  302,  281,  302,  281,  290,  305,  292,
      307,  308,  294,  293,  299,  301,  295,  296,  297,  303,
      282,  309,  288,  304,  288,  310,  311,  314,  306,  312,
      313,  315,  298,  318,  298,  307,  319,  308,  289,  321,
      320,  300,  302,  300,  302,  322,  324,  309,  299,  316,
      310,  316,  311,  314,  312,  313,  315,  301,  303,  318,
      323,  319,  328,  329,  321,  317,  320,  325,  316,  325,

      316,  322,  324,  330,  331,  332,  325,  333,  325,  334,
      335,  337,  335,  326,  317,  323,  338,  328,  339,  329,
      340,  341,  326,  335,  343,  335,  336,  344,  347,  330,
      331,  332,  333,  345,  334,  345,  337,  348,  351,  336,
      349,  338,  350,  352,  339,  340,  345,  341,  345,  346,
      343,  353,  344,  347,  354,  355,  361,  356,  357,  358,
      359,  360,  346,  348,  351,  349,  361,  350,  352,  361,
      361,  361,  361,  361,  361,  361,  361,  353,  361,  361,
      354,  355,  356,  361,  357,  358,  359,  360,   39,   39,
       39,   44,   44,   44,   46,   46,   46,   92,  361,   92,

       94,   94,   94,    5,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361
    } ;

static const flex_int16_t yy_chk[876] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    7,   19,    7,  365,    3,    4,   13,
       13,   13,   15,   25,   15,   15,   15,   16,   16,   18,
       18,   21,  337,   20,   15,  315,   20,   26,   23,   19,

       23,   21,   24,   27,   28,  248,   29,   26,   25,   27,
       23,   31,  241,   24,   24,  183,   62,   21,   20,   30,
       15,   20,   26,   23,   32,   23,   21,   34,   24,   27,
       28,   29,   26,   30,   27,   23,   31,   41,   24,   24,
       32,   33,   62,   41,   34,   30,   42,   41,   42,   33,
       32,  160,   33,   34,   49,   49,   49,   63,   30,   60,
       51,   51,   51,   65,   49,   32,   61,   33,   64,   34,
       51,   66,   92,   64,   33,   67,   52,   33,   52,   52,
       52,   53,   53,   63,   60,   53,   53,   53,   52,   65,
       49,   61,   68,   64,   69,   70,   51,   66,   64,   71,

       67,   72,   73,   74,   75,   46,   76,   77,   78,   79,
       80,   44,   81,   82,   52,   83,   84,   85,   68,   69,
       70,   87,  101,  101,  101,   71,   72,   73,   74,   39,
       75,   76,   77,   78,   79,   86,   80,   81,   82,   86,
       83,   84,   88,   85,   89,   90,   88,   87,   89,   90,
       38,   94,   96,   99,   99,   99,   37,   94,   96,  103,
       86,   94,   96,   99,   86,   36,   35,   88,  104,   89,
       90,   88,  105,   89,   90,   98,   98,  106,  107,   98,
       98,   98,  100,  100,  108,  103,  100,  100,  100,   99,
      102,  102,  102,  104,  109,  110,  112,  110,  105,  113,

      114,  115,  106,  107,  116,   17,  117,  118,  119,  120,
      108,  110,  121,  119,  122,  124,  125,  126,  131,  109,
      127,  112,  128,  129,  113,  132,  114,  115,  133,  134,
      116,  117,  135,  118,  136,  120,  137,  138,  121,  119,
      122,  124,  125,  126,  131,  127,  144,  128,  129,   14,
       12,  132,   11,  133,  134,   10,  145,  135,  146,  136,
      148,  137,  138,  139,  139,  139,  140,  140,  140,  141,
      141,  149,  144,  141,  141,  141,  142,  142,  142,  143,
      143,  143,  145,  146,  150,  148,  151,  154,  151,  157,
      158,  157,  159,    9,  161,  162,  149,  163,  164,    5,

      165,  166,  151,  168,  170,  157,  167,  171,  167,  172,
      150,  173,  154,  174,  175,  158,  176,  177,  159,  161,
      162,  178,  167,  163,  164,  165,  166,  182,  168,  170,
      179,  179,  179,  171,  172,  181,  173,  181,  174,  175,
      184,  176,  177,  180,  180,  180,  178,  185,  186,  191,
      188,  181,  188,  182,  193,  194,    0,  195,  196,  197,
      199,  198,  199,  201,  203,  184,  188,  204,  202,  205,
      202,  206,  185,  186,  191,  207,  199,  202,  208,  209,
      193,  194,  195,  196,  202,  197,  198,  210,  201,  203,
      211,  213,  211,  204,  214,  205,  215,  206,  216,  217,

      219,  207,  220,  224,  208,  209,  211,  222,  223,  225,
      221,  231,  221,  210,  230,  226,  213,  226,  227,  233,
      214,  235,  215,  216,  217,  219,  221,  227,  220,  224,
      237,  226,  222,  223,  229,  225,  229,  231,  232,  230,
      232,  234,  238,  234,  227,  233,  236,  235,  236,  239,
      229,  240,  227,  242,  232,  237,  243,  234,  244,  246,
      244,  247,  236,  249,    0,  250,  251,  238,  252,  254,
      252,  255,  258,  261,  244,  239,  240,    0,  265,  242,
      267,  243,  266,  268,  252,  246,  256,  247,  256,  249,
      250,  251,  269,  259,  254,  259,  255,  258,  261,  262,

      272,  262,  256,  264,  265,  264,  267,  266,  268,  259,
      270,  271,  270,  284,  273,  262,  274,  269,  273,  264,
      275,  276,  277,    0,    0,  272,  270,  283,  278,  279,
      278,  279,  285,  280,  281,  280,  281,  271,  284,  273,
      286,  287,  274,  273,  278,  279,  275,  276,  277,  280,
      281,  291,  288,  283,  288,  292,  293,  296,  285,  294,
      295,  297,  298,  306,  298,  286,  307,  287,  288,  309,
      308,  300,  302,  300,  302,  310,  313,  291,  298,  305,
      292,  305,  293,  296,  294,  295,  297,  300,  302,  306,
      311,  307,  318,  319,  309,  305,  308,  314,  316,  314,

      316,  310,  313,  321,  322,  323,  325,  324,  325,  327,
      329,  330,  329,  314,  316,  311,  331,  318,  332,  319,
      333,  334,  325,  335,  338,  335,  329,  339,  341,  321,
      322,  323,  324,  340,  327,  340,  330,  342,  347,  335,
      343,  331,  344,  348,  332,  333,  345,  334,  345,  340,
      338,  349,  339,  341,  350,  352,    0,  353,  354,  355,
      356,  359,  345,  342,  347,  343,    0,  344,  348,    0,
        0,    0,    0,    0,    0,    0,    0,  349,    0,    0,
      350,  352,  353,    0,  354,  355,  356,  359,  362,  362,
      362,  363,  363,  363,  364,  364,  364,  366,    0,  366,

      367,  367,  367,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
/*
    This file is part of the FElt finite element analysis package.
    Copyright (C) 1993,1994 Jason I. Gobat and Darren C. Atkinson

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

/************************************************************************
 * File:	lexer.l							*
 *									*
 * Description:	This file contains the flex specification for the	*
 *		lexical analyzer for the corduroy element generator.	*
 ************************************************************************/

# include <stdio.h>
# include <string.h>
# include <stdlib.h>
# include "error.h"
# include "geninput.h"
# include "parser.hpp"

static char *filename;
static void  update_line (void);
#line 1054 "lexer.c"

#line 1056 "lexer.c"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 47 "lexer.l"




#line 52 "lexer.l"
/* Section headings */


#line 1283 "lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 362 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 804 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "lexer.l"
{return LINE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 56 "lexer.l"
{return GRID;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 57 "lexer.l"
{return QUADGRID;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 58 "lexer.l"
{return BRICKGRID;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 59 "lexer.l"
{return TRIMESH;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 60 "lexer.l"
{return END;}
	YY_BREAK

/* Reserved words (in expression or right hand side of assignment) */

case 7:
YY_RULE_SETUP
#line 67 "lexer.l"
{return SIN;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "lexer.l"
{return COS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "lexer.l"
{return TAN;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "lexer.l"
{return POW;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "lexer.l"
{return EXP;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "lexer.l"
{return LOG;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "lexer.l"
{return LOG10;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "lexer.l"
{return SQRT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "lexer.l"
{return HYPOT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "lexer.l"
{return FLOOR;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "lexer.l"
{return CEIL;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "lexer.l"
{return FMOD;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "lexer.l"
{return FABS;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "lexer.l"
{return LINEAR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "lexer.l"
{return LOGARITHMIC;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "lexer.l"
{return REVERSE_LOGARITHMIC;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "lexer.l"
{return COSINUSOIDAL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "lexer.l"
{return SINUSOIDAL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "lexer.l"
{return PARABOLIC;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "lexer.l"
{return REVERSE_PARABOLIC;}
	YY_BREAK

/* Assignments */

case 27:
YY_RULE_SETUP
#line 92 "lexer.l"
{return NODE_EQ;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 93 "lexer.l"
{return ELEMENT_EQ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 94 "lexer.l"
{return CONSTRAINT_EQ;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 95 "lexer.l"
{return MATERIAL_EQ;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 96 "lexer.l"
{return TYPE_EQ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 97 "lexer.l"
{return START_EQ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 98 "lexer.l"
{return END_EQ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 99 "lexer.l"
{return NUMBER_EQ;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 100 "lexer.l"
{return RULE_EQ;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "lexer.l"
{return X_NUMBER_EQ;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "lexer.l"
{return Y_NUMBER_EQ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "lexer.l"
{return Z_NUMBER_EQ;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "lexer.l"
{return X_RULE_EQ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "lexer.l"
{return Y_RULE_EQ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "lexer.l"
{return Z_RULE_EQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "lexer.l"
{return TARGET_EQ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "lexer.l"
{return ALPHA_EQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 109 "lexer.l"
{return BOUNDARY_EQ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "lexer.l"
{return HOLE_EQ;}
	YY_BREAK

/* Operators */

case 46:
YY_RULE_SETUP
#line 117 "lexer.l"
{return AND;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 118 "lexer.l"
{return OR;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 119 "lexer.l"
{return EQUALS;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 120 "lexer.l"
{return NEQUAL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 121 "lexer.l"
{return LT_EQ;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 122 "lexer.l"
{return GT_EQ;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 123 "lexer.l"
{return LSHIFT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 124 "lexer.l"
{return RSHIFT;}
	YY_BREAK

/* Numbers and names */

case 54:
YY_RULE_SETUP
#line 131 "lexer.l"
{cord_yylval.i = atoi (yytext); return INTEGER;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 132 "lexer.l"
{cord_yylval.d = atof (yytext); return DOUBLE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 133 "lexer.l"
{cord_yylval.d = atof (yytext); return DOUBLE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 134 "lexer.l"
{cord_yylval.d = atof (yytext); return DOUBLE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "lexer.l"
{cord_yylval.s = strdup (yytext); return NAME;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 137 "lexer.l"
{cord_yylval.s = strdup (yytext + 1);
				 cord_yylval.s [yyleng - 2] = 0; return NAME;}
	YY_BREAK

/* Comments, white space, and remaining preprocessor lines (the comment
   rules are straight from the flex documentation). */

case 60:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 146 "lexer.l"
{update_line ( );}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 147 "lexer.l"
{}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 148 "lexer.l"
{geninput.line ++;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 149 "lexer.l"
{BEGIN comment;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 151 "lexer.l"
{}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 152 "lexer.l"
{geninput.line ++;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 153 "lexer.l"
{}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 154 "lexer.l"
{geninput.line ++;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 155 "lexer.l"
{BEGIN INITIAL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 157 "lexer.l"
{return *yytext;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 159 "lexer.l"
ECHO;
	YY_BREAK
#line 1714 "lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 362 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 362 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 361);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 159 "lexer.l"


/************************************************************************
 * Function:	yyerror							*
 *									*
 * Description:	Writes a syntax error message reporting the unexpected	*
 *		token.							*
 ************************************************************************/

void cord_yyerror (const char *msg)
{
    extern int cord_yychar;


    if (cord_yychar)
	error ("parse error before `%s'", yytext);
    else
	error ("parse error before end of input");
}


/************************************************************************
 * Function:	init_cord_lexer						*
 *									*
 * Description:	Initializes the lexer for a new file.			*
 ************************************************************************/

void init_cord_lexer (FILE *fp)
{
    static int first_time = 1;


    if (first_time) {
	first_time = 0;
	yyin = fp;
    } else
	yyrestart (fp);

    filename = geninput.filename;
}


/************************************************************************
 * Function:	update_line						*
 *									*
 * Description:	Updates the current line and file from a preprocessor	*
 *		directive.						*
 ************************************************************************/

static void update_line (void)
{
    char       *ptr1;
    char       *ptr2;
    int		line;
    static char include_filename [256];


    ptr2 = include_filename;
    line = strtol (yytext + 1, &ptr1, 10) - 1;

    if (ptr1) {
	geninput.line = line;

	while (*ptr1 && *ptr1 ++ != '"');

	if (*ptr1)
	    geninput.filename = filename;

	while (*ptr1 && *ptr1 != '"')
	    *ptr2 ++ = *ptr1 ++;

	*ptr2 = 0;
	if (ptr2 != include_filename)
	    geninput.filename = include_filename;
    }
}

#if 0
# undef yywrap
int yywrap (void) {
    if (0) unput (0);
    return 1;
}
#endif

